export const BEERS_ERRORED = "BEERS_ERRORED";
export const BEERS_LOADING = "BEERS_LOADING";
export const BEERS_SUCCEEDED = "BEERS_SUCCEEDED";
export const BEER_UPDATE_SUCCEEDED = "BEER_UPDATE_SUCCEEDED";
export const BEER_DELETE_SUCCEEDED = "BEER_DELETE_SUCCEEDED";
export const WINES_ERRORED = "WINES_ERRORED";
export const WINES_LOADING = "WINES_LOADING";
export const WINES_SUCCEEDED = "WINES_SUCCEEDED";